// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.20;

/**
 * @title IRedstoneAggregator
 * @notice Base interface for RedStone price oracle aggregators
 * @dev Interface for RedStone price feed contracts
 * @custom:tags oracle,redstone,price-feed,aggregator
 */
interface IRedstoneAggregator {
    error GetRoundDataCanBeOnlyCalledWithLatestRound(uint80 requestedRoundId);
    error UnsafeUintToIntConversion(uint256 value);
    event Initialized(uint8 version);

    function decimals() external pure returns (uint8);

    function description() external view returns (string memory);

    function getDataFeedId() external view returns (bytes32);

    function getPriceFeedAdapter() external view returns (address);

    function getRoundData(uint80 requestedRoundId)
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        );

    function initialize() external;

    function latestAnswer() external view returns (int256);

    function latestRound() external pure returns (uint80);

    function latestRoundData()
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        );

    function version() external pure returns (uint256);
}
