// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.20;

/**
 * @title ICatalogFactory
 * @notice Factory to create Catalog instances, necessary to configure composability and equippability of NFTs (ERC6220)
 * @dev Interface for deploying and managing RMRK catalog contracts
 * @custom:katana 0xC0137140B2D2a146d20dBbb0153e5Ac1048f30E3
 * @custom:bokuto 0xC0137140B2D2a146d20dBbb0153e5Ac1048f30E3
 * @custom:tags nft,erc721,rmrk,catalog,factory
 */
interface ICatalogFactory {
    event CatalogDeployed(address indexed deployer, address indexed catalog);

    function deployCatalog(string memory metadataURI, string memory type_)
        external
        returns (address);

    function getDeployerCatalogAtIndex(address deployer, uint256 index)
        external
        view
        returns (address catalogAddress);

    function getDeployerCatalogs(address deployer)
        external
        view
        returns (address[] memory);

    function getLastDeployerCatalog(address deployer)
        external
        view
        returns (address catalogAddress);

    function getTotalDeployerCatalogs(address deployer)
        external
        view
        returns (uint256 total);
}