name: Setup and Install

inputs:
  bun-version:
    required: false
    default: 'latest'
  working-directory:
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
        
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun install