name: Build project

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Install
        uses: ./.github/actions/install

      - name: Build
        run: bun run build:all

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/